import express from 'express';
import Todo from '../models/Todo.js';
import { authenticateToken } from '../middleware/auth.js';
import { asyncHandler } from '../middleware/errorHandler.js';

const router = express.Router();

// Get todos for a specific date (default: today)
router.get('/', authenticateToken, asyncHandler(async (req, res) => {
  const { date = new Date().toISOString().split('T')[0] } = req.query;
  const userId = req.user.username;

  const todos = await Todo.find({ userId, dueDate: date })
    .select('_id title notes status order dueDate autoGenerated attachedToSandclock')
    .sort({ order: 1, createdAt: 1 })
    .lean();

  res.json({
    success: true,
    todos
  });
}));

// Get carry-over todos (previous days) with pagination
router.get('/carry-overs', authenticateToken, asyncHandler(async (req, res) => {
  const { cursor, limit = 20, includeDone = false } = req.query;
  const userId = req.user.username;

  let query = { 
    userId, 
    dueDate: { $lt: new Date().toISOString().split('T')[0] } 
  };

  if (!includeDone) {
    query.status = 'pending';
  }

  if (cursor) {
    query._id = { $lt: cursor };
  }

  const todos = await Todo.find(query)
    .select('_id title notes status dueDate sourceDate autoGenerated')
    .sort({ dueDate: -1, order: 1 })
    .limit(parseInt(limit))
    .lean();

  res.json({
    success: true,
    todos,
    nextCursor: todos.length === parseInt(limit) ? todos[todos.length - 1]._id : null
  });
}));

// Create a new todo
router.post('/', authenticateToken, asyncHandler(async (req, res) => {
  const { title, notes, dueDate = new Date().toISOString().split('T')[0] } = req.body;
  const userId = req.user.username;

  if (!title) {
    return res.status(400).json({
      success: false,
      error: 'Title is required'
    });
  }

  // Get the next order number for the dueDate
  const lastTodo = await Todo.findOne({ userId, dueDate })
    .sort({ order: -1 })
    .select('order')
    .lean();

  const order = (lastTodo?.order || 0) + 1;

  const todo = new Todo({
    userId,
    title,
    notes,
    dueDate,
    sourceDate: dueDate,
    order,
    autoGenerated: false
  });

  await todo.save();

  res.status(201).json({
    success: true,
    todo
  });
}));

// Auto-generate 3 todos for the day
router.post('/auto-generate', authenticateToken, asyncHandler(async (req, res) => {
  const userId = req.user.username;
  const dueDate = new Date().toISOString().split('T')[0];

  // Check if already auto-generated today
  const existingAutoGenerated = await Todo.findOne({ 
    userId, 
    dueDate, 
    autoGenerated: true 
  });

  if (existingAutoGenerated) {
    return res.status(400).json({
      success: false,
      error: 'Auto-generated todos already created for today'
    });
  }

  // Get the next order number
  const lastTodo = await Todo.findOne({ userId, dueDate })
    .sort({ order: -1 })
    .select('order')
    .lean();

  let order = (lastTodo?.order || 0) + 1;

  const autoTodos = [
    {
      title: 'Review yesterday\'s progress',
      notes: 'Spend 10 minutes reviewing what you accomplished yesterday.',
      dueDate,
      sourceDate: dueDate,
      order: order++,
      autoGenerated: true
    },
    {
      title: 'Plan today\'s top 3 priorities',
      notes: 'Identify the most important tasks for today.',
      dueDate,
      sourceDate: dueDate,
      order: order++,
      autoGenerated: true
    },
    {
      title: 'Take a break and stretch',
      notes: 'Remember to take short breaks to maintain productivity.',
      dueDate,
      sourceDate: dueDate,
      order: order++,
      autoGenerated: true
    }
  ];

  const todos = await Todo.insertMany(autoTodos.map(todo => ({ ...todo, userId })));

  res.status(201).json({
    success: true,
    todos
  });
}));

// Update a todo
router.patch('/:id', authenticateToken, asyncHandler(async (req, res) => {
  const { id } = req.params;
  const userId = req.user.username;
  const updates = req.body;

  const todo = await Todo.findOneAndUpdate(
    { _id: id, userId },
    updates,
    { new: true, runValidators: true }
  );

  if (!todo) {
    return res.status(404).json({
      success: false,
      error: 'Todo not found'
    });
  }

  res.json({
    success: true,
    todo
  });
}));

// Bulk update for reordering
router.patch('/', authenticateToken, asyncHandler(async (req, res) => {
  const { updates } = req.body;
  const userId = req.user.username;

  const operations = updates.map(({ id, order }) => ({
    updateOne: {
      filter: { _id: id, userId },
      update: { $set: { order } }
    }
  }));

  await Todo.bulkWrite(operations);

  res.json({
    success: true,
    message: 'Todos reordered successfully'
  });
}));

// Delete a todo
router.delete('/:id', authenticateToken, asyncHandler(async (req, res) => {
  const { id } = req.params;
  const userId = req.user.username;

  const todo = await Todo.findOneAndDelete({ _id: id, userId });

  if (!todo) {
    return res.status(404).json({
      success: false,
      error: 'Todo not found'
    });
  }

  res.json({
    success: true,
    message: 'Todo deleted successfully'
  });
}));

// Attach a todo to the current sandclock session
router.post('/:id/attach', authenticateToken, asyncHandler(async (req, res) => {
  const { id } = req.params;
  const userId = req.user.username;
  const { sessionId } = req.body;

  // First, detach any currently attached todo
  await Todo.updateMany(
    { userId, 'attachedToSandclock.active': true },
    { 'attachedToSandclock.active': false }
  );

  const todo = await Todo.findOneAndUpdate(
    { _id: id, userId },
    { 
      'attachedToSandclock.active': true,
      'attachedToSandclock.sessionId': sessionId 
    },
    { new: true }
  );

  if (!todo) {
    return res.status(404).json({
      success: false,
      error: 'Todo not found'
    });
  }

  res.json({
    success: true,
    todo
  });
}));

// Detach a todo from the current sandclock session
router.post('/:id/detach', authenticateToken, asyncHandler(async (req, res) => {
  const { id } = req.params;
  const userId = req.user.username;

  const todo = await Todo.findOneAndUpdate(
    { _id: id, userId },
    { 
      'attachedToSandclock.active': false,
      'attachedToSandclock.sessionId': null 
    },
    { new: true }
  );

  if (!todo) {
    return res.status(404).json({
      success: false,
      error: 'Todo not found'
    });
  }

  res.json({
    success: true,
    todo
  });
}));

// Mark a todo as done from sandclock session completion
router.post('/:id/complete-from-sandclock', authenticateToken, asyncHandler(async (req, res) => {
  const { id } = req.params;
  const userId = req.user.username;

  const todo = await Todo.findOneAndUpdate(
    { _id: id, userId },
    { 
      status: 'done',
      'attachedToSandclock.active': false,
      'attachedToSandclock.sessionId': null 
    },
    { new: true }
  );

  if (!todo) {
    return res.status(404).json({
      success: false,
      error: 'Todo not found'
    });
  }

  res.json({
    success: true,
    todo
  });
}));

export default router;