import mongoose from 'mongoose';
import Todo from '../models/Todo.js';
import StructuredTodo from '../models/StructuredTodo.js';
import config from '../config/environment.js';

const migrateTodos = async () => {
  try {
    await mongoose.connect(config.MONGODB_URI);
    console.log('Connected to database');

    // Get all existing todos
    const todos = await Todo.find({});
    console.log(`Found ${todos.length} todos to migrate`);

    // Group todos by userId and dueDate
    const groupedTodos = todos.reduce((acc, todo) => {
      const { userId, dueDate } = todo;
      
      if (!acc[userId]) {
        acc[userId] = {};
      }
      
      if (!acc[userId][dueDate]) {
        acc[userId][dueDate] = [];
      }
      
      acc[userId][dueDate].push(todo);
      return acc;
    }, {});

    let migratedCount = 0;
    let userCount = 0;

    // Process each user
    for (const [userId, days] of Object.entries(groupedTodos)) {
      userCount++;
      console.log(`Processing user ${userCount}: ${userId}`);

      // Create or get user's structured todos
      let structuredTodo = await StructuredTodo.findOne({ userId });
      
      if (!structuredTodo) {
        structuredTodo = new StructuredTodo({
          userId,
          days: []
        });
      }

      // Process each day for this user
      for (const [date, dayTodos] of Object.entries(days)) {
        // Find or create day in structured todos
        let day = structuredTodo.days.find(d => d.date === date);
        if (!day) {
          day = { date, todos: [] };
          structuredTodo.days.push(day);
        }
        
        // Add todos to this day
        dayTodos.forEach(todo => {
          // Check if todo already exists in this day
          const todoExists = day.todos.some(existingTodo => 
            existingTodo._id.toString() === todo._id.toString()
          );
          
          if (!todoExists) {
            // Convert to new structure
            const newTodo = {
              _id: todo._id,
              title: todo.title,
              notes: todo.notes,
              status: todo.status,
              completed: todo.status === 'done',
              dueDate: todo.dueDate,
              sourceDate: todo.sourceDate,
              order: todo.order,
              autoGenerated: todo.autoGenerated,
              attachedToSandclock: todo.attachedToSandclock,
              createdAt: todo.createdAt,
              updatedAt: todo.updatedAt
            };
            
            day.todos.push(newTodo);
            migratedCount++;
          }
        });
      }

      await structuredTodo.save();
      console.log(`✓ Migrated ${dayTodos.length} todos for user: ${userId}`);
    }

    console.log(`\n🎉 Migration completed!`);
    console.log(`📊 Users processed: ${userCount}`);
    console.log(`📝 Total todos migrated: ${migratedCount}`);
    
    // Optional: Verify migration
    const totalStructuredTodos = await StructuredTodo.aggregate([
      { $unwind: '$days' },
      { $unwind: '$days.todos' },
      { $count: 'total' }
    ]);
    
    console.log(`✅ Total todos in new structure: ${totalStructuredTodos[0]?.total || 0}`);

  } catch (error) {
    console.error('❌ Migration error:', error);
  } finally {
    await mongoose.disconnect();
    console.log('🔌 Disconnected from database');
  }
};

// Run migration if script is executed directly
if (import.meta.url === `file://${process.argv[1]}`) {
  migrateTodos();
}

export default migrateTodos;