import mongoose from 'mongoose';
import Todo from '../models/Todo.js';
import StructuredTodo from '../models/StructuredTodo.js';
import config from '../config/environment.js';

console.log('🚀 Starting todo migration...');

const migrateTodos = async () => {
  let connection;
  try {
    console.log('📡 Connecting to database...');
    connection = await mongoose.connect(config.MONGODB_URI);
    console.log('✅ Connected to database:', mongoose.connection.db.databaseName);

    // Get all existing todos
    console.log('📋 Fetching existing todos...');
    const todos = await Todo.find({});
    console.log(`📊 Found ${todos.length} todos to migrate`);

    if (todos.length === 0) {
      console.log('ℹ️ No todos found to migrate');
      return;
    }

    // Get unique users
    const userIds = [...new Set(todos.map(todo => todo.userId))];
    console.log(`👥 Found ${userIds.length} users:`, userIds);

    let totalMigrated = 0;
    let userCount = 0;

    // Process each user
    for (const userId of userIds) {
      userCount++;
      console.log(`\n--- Processing user ${userCount}/${userIds.length}: ${userId} ---`);

      // Get user's todos
      const userTodos = todos.filter(todo => todo.userId === userId);
      console.log(`📝 User has ${userTodos.length} todos`);

      // Group todos by date
      const todosByDate = {};
      userTodos.forEach(todo => {
        if (!todosByDate[todo.dueDate]) {
          todosByDate[todo.dueDate] = [];
        }
        todosByDate[todo.dueDate].push(todo);
      });

      console.log(`📅 Found ${Object.keys(todosByDate).length} unique dates`);

      // Create days array
      const days = Object.entries(todosByDate).map(([date, dateTodos]) => {
        const todosForDay = dateTodos.map(todo => ({
          _id: todo._id,
          title: todo.title,
          notes: todo.notes,
          status: todo.status,
          completed: todo.status === 'done',
          dueDate: todo.dueDate,
          sourceDate: todo.sourceDate,
          order: todo.order,
          autoGenerated: todo.autoGenerated,
          attachedToSandclock: todo.attachedToSandclock,
          createdAt: todo.createdAt,
          updatedAt: todo.updatedAt
        }));

        return {
          date,
          todos: todosForDay
        };
      });

      // Check if structured todo already exists
      let structuredTodo = await StructuredTodo.findOne({ userId });
      
      if (structuredTodo) {
        console.log(`🔄 Updating existing structured todos for user ${userId}`);
        structuredTodo.days = days;
      } else {
        console.log(`🆕 Creating new structured todos for user ${userId}`);
        structuredTodo = new StructuredTodo({
          userId,
          days,
          lastProcessed: null
        });
      }

      await structuredTodo.save();
      totalMigrated += userTodos.length;
      console.log(`✅ Successfully migrated ${userTodos.length} todos for ${userId}`);
    }

    console.log('\n🎉 MIGRATION COMPLETED SUCCESSFULLY!');
    console.log('=====================================');
    console.log(`📊 Total users processed: ${userCount}`);
    console.log(`📝 Total todos migrated: ${totalMigrated}`);
    console.log(`🏁 Original todo count: ${todos.length}`);

    // Verify counts match
    if (totalMigrated === todos.length) {
      console.log('✅ All todos migrated successfully!');
    } else {
      console.log(`⚠️  Count mismatch: expected ${todos.length}, migrated ${totalMigrated}`);
    }

  } catch (error) {
    console.error('❌ MIGRATION FAILED:', error);
    console.error('Error details:', error.message);
    if (error.stack) {
      console.error('Stack trace:', error.stack);
    }
  } finally {
    if (mongoose.connection.readyState !== 0) {
      await mongoose.disconnect();
      console.log('🔌 Disconnected from database');
    }
    console.log('🏁 Migration script finished');
  }
};

// Run the migration
migrateTodos();