const mongoose = require('mongoose');
const Todo = require('../models/Todo.js');
const StructuredTodo = require('../models/StructuredTodo.js');
const config = require('../config/environment.js');

console.log('🚀 Starting todo migration (CJS version)...');

const migrateTodos = async () => {
  try {
    console.log('📡 Connecting to database...');
    await mongoose.connect(config.MONGODB_URI);
    console.log('✅ Connected to database');

    // Get all existing todos
    console.log('📋 Fetching existing todos...');
    const todos = await Todo.find({});
    console.log(`📊 Found ${todos.length} todos to migrate`);

    if (todos.length === 0) {
      console.log('ℹ️ No todos found to migrate');
      return;
    }

    // Get unique users
    const userIds = [...new Set(todos.map(todo => todo.userId))];
    console.log(`👥 Found ${userIds.length} users`);

    let totalMigrated = 0;

    for (const userId of userIds) {
      console.log(`\n👤 Processing user: ${userId}`);

      const userTodos = todos.filter(todo => todo.userId === userId);
      
      // Group by date
      const days = [];
      const dateMap = new Map();

      userTodos.forEach(todo => {
        if (!dateMap.has(todo.dueDate)) {
          dateMap.set(todo.dueDate, []);
        }
        dateMap.get(todo.dueDate).push({
          _id: todo._id,
          title: todo.title,
          notes: todo.notes,
          status: todo.status,
          completed: todo.status === 'done',
          dueDate: todo.dueDate,
          sourceDate: todo.sourceDate,
          order: todo.order,
          autoGenerated: todo.autoGenerated,
          attachedToSandclock: todo.attachedToSandclock,
          createdAt: todo.createdAt,
          updatedAt: todo.updatedAt
        });
      });

      // Convert map to days array
      dateMap.forEach((todos, date) => {
        days.push({ date, todos });
      });

      // Create or update structured todo
      await StructuredTodo.findOneAndUpdate(
        { userId },
        { 
          userId,
          days,
          lastProcessed: null
        },
        { upsert: true }
      );

      totalMigrated += userTodos.length;
      console.log(`✅ Migrated ${userTodos.length} todos for ${userId}`);
    }

    console.log('\n🎉 MIGRATION COMPLETED!');
    console.log(`📝 Total todos migrated: ${totalMigrated}`);

  } catch (error) {
    console.error('❌ Migration error:', error);
  } finally {
    await mongoose.disconnect();
    console.log('🔌 Disconnected from database');
  }
};

migrateTodos();