import mongoose from 'mongoose';

const todoSchema = new mongoose.Schema({
  userId: {
    type: String,
    required: true,
    ref: 'User',
    index: true
  },
  title: {
    type: String,
    required: true,
    maxlength: 200
  },
  notes: {
    type: String,
    maxlength: 2000,
    default: ''
  },
  status: {
    type: String,
    enum: ['pending', 'done'],
    default: 'pending',
    index: true
  },
  dueDate: {
    type: String, // 'YYYY-MM-DD'
    required: true
  },
  sourceDate: {
    type: String, // 'YYYY-MM-DD' - the date the todo was first created
    required: true
  },
  order: {
    type: Number,
    default: 0
  },
  autoGenerated: {
    type: Boolean,
    default: false
  },
  attachedToSandclock: {
    active: {
      type: Boolean,
      default: false
    },
    sessionId: {
      type: String,
      default: null
    }
  }
}, {
  timestamps: true
});

// Compound indexes for efficient querying
todoSchema.index({ userId: 1, dueDate: 1 });
todoSchema.index({ userId: 1, status: 1, dueDate: 1 });

export default mongoose.model('Todo', todoSchema);