import mongoose from 'mongoose';

const todoSchema = new mongoose.Schema({
  userId: {
    type: String,
    required: true,
    ref: 'User',
    index: true
  },
  title: {
    type: String,
    required: true,
    trim: true,
    maxlength: 200
  },
  notes: {
    type: String,
    trim: true,
    maxlength: 2000,
    default: ''
  },
  status: {
    type: String,
    enum: ['pending', 'done'],
    default: 'pending',
    index: true
  },
  dueDate: {
    type: String, // 'YYYY-MM-DD'
    required: true,
    index: true
  },
  sourceDate: {
    type: String, // 'YYYY-MM-DD' - the date the todo was first created
    required: true
  },
  order: {
    type: Number,
    default: 0,
    min: 0
  },
  autoGenerated: {
    type: Boolean,
    default: false
  },
  attachedToSandclock: {
    active: {
      type: Boolean,
      default: false
    },
    sessionId: {
      type: String,
      default: null,
      index: true
    }
  }
}, {
  timestamps: true
});

// Compound indexes for efficient querying
todoSchema.index({ userId: 1, dueDate: 1 });
todoSchema.index({ userId: 1, status: 1, dueDate: 1 });
todoSchema.index({ userId: 1, 'attachedToSandclock.active': 1 });
todoSchema.index({ userId: 1, autoGenerated: 1, dueDate: 1 });

// Virtual for isOverdue
todoSchema.virtual('isOverdue').get(function() {
  return this.status === 'pending' && this.dueDate < new Date().toISOString().split('T')[0];
});

// Instance method to mark as complete
todoSchema.methods.markComplete = function() {
  this.status = 'done';
  this.attachedToSandclock.active = false;
  this.attachedToSandclock.sessionId = null;
  return this.save();
};

// Instance method to attach to sandclock
todoSchema.methods.attachToSandclock = function(sessionId) {
  this.attachedToSandclock.active = true;
  this.attachedToSandclock.sessionId = sessionId;
  return this.save();
};

// Static method to get today's todos
todoSchema.statics.getTodayTodos = function(userId) {
  const today = new Date().toISOString().split('T')[0];
  return this.find({ userId, dueDate: today })
    .sort({ order: 1, createdAt: 1 })
    .lean();
};

// Static method to get todos by date range
todoSchema.statics.getByDateRange = function(userId, startDate, endDate, options = {}) {
  const { includeDone = true, limit = 50 } = options;
  
  let query = { userId, dueDate: { $gte: startDate, $lte: endDate } };
  
  if (!includeDone) {
    query.status = 'pending';
  }
  
  return this.find(query)
    .sort({ dueDate: 1, order: 1 })
    .limit(limit)
    .lean();
};

// Static method to get completion stats
todoSchema.statics.getCompletionStats = function(userId) {
  return this.aggregate([
    { $match: { userId } },
    {
      $group: {
        _id: '$status',
        count: { $sum: 1 },
        recent: { $max: '$updatedAt' }
      }
    }
  ]);
};

export default mongoose.model('Todo', todoSchema);